### ISSUE TITLE
GetTransfers API not suppert 'skip' and 'limit' params

### ISSUE THREAD

**Issue by IsQiao** [eoscafe/hyperion-api#5]
![image](https://user-images.githubusercontent.com/8536046/57969337-a028b600-79a8-11e9-8cd1-93bfde8ecd71.png)

https://github.com/eoscafe/hyperion-api/blob/ec54b55fac4c29a30656deacaef72ad118498237/src/jsonrpc.ts#L392

**Comment by IsQiao** [comment]
the PR to fixed it.
https://github.com/eoscafe/hyperion-api/pull/6

**Comment by jafri** [comment]
Closed in 21bf6dc
